Repository kwynns/test, pull requests merged in 2019-02, with the labels that each got.

#115 mdow
  src/js/routes.js
Labels: Status: Approved, Type: Bug

#106 mdow bug
  src/js/routes.js
Labels: Type: Bug

#114 Bug/100/issue dfgdfg
  src/index.html
Labels: Priority: High, Status: Approved, Type: Bug

#117 Bug/100/stuff
  src/js/reducers/friendList.js
  src/js/reducers/index.js
Labels: Priority: High, Status: Review Needed, Type: Bug

#118 meow
  src/js/actions/FriendsActions.js
Labels: Priority: Low, Status: Review Needed, Type: Bug

#119 meow
  src/js/main.js
Labels: Priority: Medium, Status: Review Needed, Type: Bug

#121 moe
  src/js/main.js
Labels: Priority: Medium, Status: Review Needed, Type: Bug
